apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: flask
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/aleemahmad0508/platform.git
    targetRevision: master
    path: applications/flask/helm

  destination:
    server: https://kubernetes.default.svc
    namespace: flaskk

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true