apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: mcp-server
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/aleemahmad0508/platform.git
    targetRevision: master
    path: shared/ai-ops/mcp-k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true