apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-mcp

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: mcp

  template:
    metadata:
      labels:
        app: mcp

    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}

      containers:
        - name: mcp-server

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}