apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: {{ .Release.Name }}-mcp-role

rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - services
      - endpoints
      - events
    verbs:
      - get
      - list
      - watch

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch